/* File AutoVer.h
   Do NOT edit this file.
   Update with AutoVer commands.
   Last updated on December 31, 2025
*/
#include <string>
#ifndef AUTOVER_H
#define AUTOVER_H
const unsigned int AutoVerMajor=1;
const unsigned int AutoVerMinor=2;
const unsigned int AutoVerPatch=2;
const std::string AutoVerString="1.2.2";
#endif
 
